### ISSUE TITLE
Feature/Fixes Roadmap

### ISSUE THREAD

**Issue by chryton** [chryton/gulp-draftsman#1]
## Fixes
- [x] Fix initial nesting issue
- [ ] Make gulp plugin work
- [ ] Make built JSON file valid JSON or switch to a built JS file
- [ ] Add Commandline functionality https://github.com/tj/commander.js ?
- [ ] make index JS file to be `import (rebuilt-file-name.js) ` for each rebuilt file since monolith file won't exist
## Planned Enhancements
- [ ] Add Base64 decode option (looking at requiring this module https://www.npmjs.com/package/js-base64)
- [ ] Add better options management
## Maybe Enhancements
- [ ] Port to Grunt
- [ ] Pull tasks out to own repo or gist
